### ISSUE TITLE
Strange http error

### ISSUE THREAD

**Issue by EnterNewName** [SpectrixOfficial/spectrixofficial.github.io#1]
it loads but it is showing like no style hardly
https://i.imgur.com/9byS67G.png

**Comment by EnterNewName** [comment]
never mind its not http

**Comment by SpectrixOfficial** [comment]
This was your internet. Nothing to do with http. Please don't randomly open issues

**Comment by EnterNewName** [comment]
its not my internet
https://i.imgur.com/RdYTbFS.png

**Comment by notBanii** [comment]
Something is up with your browser. This happened with my old computer.

**Comment by SpectrixOfficial** [comment]
Sorry, _seems it's something to do with **https..._**

**Comment by EnterNewName** [comment]
its not my internet nor browser, it doesnt work with firefox either

**Comment by SpectrixOfficial** [comment]
It's the browsers. They think that my site is trying to load unsafe scripts. I thought I configured https, but it seems not. 

http://prntscr.com/ks4rd0

**Comment by EnterNewName** [comment]
i don't trust your site >:(

**Comment by EnterNewName** [comment]
you should either add https:// or just set it to `spectrix.me`

**Comment by SpectrixOfficial** [comment]
There's actually a big problem here, I've tried a lot. I just need more time that's all

**Comment by SpectrixOfficial** [comment]
Ok, so I actually did some stuff a few days ago, let me update this:

The site has https now, but it's still not loading some scripts on the main page (css, js etc) because it comes from many different places that aren't http and it's just too complicated as I didn't actually make this theme, so I'm going to stop using it and just make a simpler website. I'll use jekyll again for a Spectrum help page.

**Comment by SpectrixOfficial** [comment]
Forgot to mention but a couple of hours ago I fixed this. It was a problem with the CSS files getting confused with the different domain names. But that wasn't all, cloudfare wasn't configured correctly and a while bunch of other stuff.

But now I've learnt and I hope to never make this mistake again
